# Generated by Django 3.0.6 on 2020-05-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='messages',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='messages',
            field=models.ManyToManyField(blank=True, to='chat.Message'),
        ),
    ]
